import React from 'react'


const About = () => {

  return (
    <div className="ui container centered" >
    <br></br>
    <br></br>
      <div cla>
      <b>Welcome to STREAK Trivia!</b>
      <br></br>
      <br></br>
      The goal is simple: get as many questions correct in a row as possible, forming a STREAK!
      <br></br>
      Your highest streak is recorded and ranked amongst all users, so bragging rights are all <br></br> yours if you
      can take the top spot.

      <br></br>
      <br></br>
      <b>Submit a Question!</b><br></br>
      <br></br>
      Our goal is to create a database of robust trivia questions entirely generated by an enthusiastic <br></br>
      trivia fans like you, so submit your own challenging questions to put an end to any long opponent
      <br></br>streaks!

      <br></br>
      <br></br>
      Sign up and let the game(s) begin!
      </div>

    </div>
  );

}

export default About
